image: registry.gitlab.com/zyehex/port/node

stages:
  - test
  - build
  - deploy
  - cleanup

cache:
  paths:
    - node_modules/

test:
  stage: test
  before_script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Deploying ${CI_PROJECT_NAME} ${CI_COMMIT_TAG} \n${CI_PIPELINE_URL}\"}" ${ALERT_WEBHOOK}'
    - yarn
  script:
    - yarn test

build:package:
  stage: build
  script: yarn build
  artifacts:
    paths:
      - dist/
  only:
    - tags

build:storybook:
  stage: build
  script: yarn build:storybook
  artifacts:
    paths:
      - storybook-static/
  only:
    - tags

deploy:package:
  stage: deploy
  dependencies:
    - build:package
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm publish

deploy:storybook:
  image: python:alpine
  stage: deploy
  dependencies:
    - build:storybook
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${AWS_BUCKET_NAME}/ --recursive
    - aws s3 cp storybook-static s3://${AWS_BUCKET_NAME} --recursive --acl public-read
  environment:
    name: production
    url: http://samurai.zyehex.com
  cache: {}
  only:
    - tags

alert:post:
  stage: cleanup
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"${CI_PROJECT_NAME} successfully deployed\"}" ${ALERT_WEBHOOK}'
  cache: {}
  only:
    - tags

alert:error:
  stage: cleanup
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"<!channel> ${CI_PROJECT_NAME} deployment failed for ${CI_PIPELINE_ID}\n${CI_PIPELINE_URL}\"}" ${ALERT_WEBHOOK}'
  when: on_failure
  cache: {}
  only:
    - tags
